name: movie_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies: 
  flutter:
    sdk: flutter
  
  #Core
  equatable: ^2.0.5

  #Network
  dio: ^5.3.3  
  vexana: any

  #State
  flutter_bloc: ^8.1.3
  provider: ^6.1.1

  #Config
  easy_localization: ^3.0.3
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  #Utility
  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  animations: ^2.0.11
  easy_logger: ^0.0.2
  logger: ^2.0.2+1

 
  #Cache
  shared_preferences: ^2.2.2

  #Modules
  gen:
    path: module/gen
  
  widgets:
    path: module/widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6  
  pedantic_mono: any
  very_good_analysis: ^5.1.0
  device_preview: ^1.1.0

flutter:


  uses-material-design: true

  assets:
    - asset/translations/
